### ISSUE TITLE
Add `all_dir_paths` and revert `dir_paths` to 0.3 behaviour

### ISSUE THREAD

**Issue by ncoghlan** [ncoghlan/walkdir#12]
As proposed in https://github.com/ncoghlan/walkdir/issues/4#issuecomment-216409157 I want to move the current `dir_paths` implementation to a new function, `all_dir_paths`, and revert `dir_paths` to only reporting directories that are visited by the underlying walk.

This means that `dir_paths` with a depth limited walk will behave as expected (reporting only directories down to the specified level), while the new `all_dir_paths` will report an additional level further down (since it reports visited directories _and_ the subdirectories of those directories).

**Updated**: original suggestion was for `subdir_paths`, I've changed that to `all_dir_paths` instead

**Comment by palaviv** [comment]
The only problem I can see here is that `dir_paths` will not yield symlinks to directory's.

**Comment by ncoghlan** [comment]
Right, but if the documentation is updated to specify that it reports the directories the underlying walk visits, that will be the correct behaviour - it will report them if `followlinks` is true, and omit them otherwise.

By contrast, `subdir_paths` would always include them, regardless of whether or not `followlinks` was set in the underlying walk.

That and the different handling of subdirectories of leaf directories in a depth limited walk would then be the two differences pointed out in the `subdir_paths` documentation.

**Comment by palaviv** [comment]
That sounds great :+1:

**Comment by ncoghlan** [comment]
The `subdir_paths` name was bothering me, as the function still emits the paths to any root directories as part of its output. However, I realised the following tiering could work:

`dir_paths`: directories visited by the underlying walk
`file_paths`: files in directories visited by the underlying walk
`all_dir_paths`: `dir_paths` + subdirectories of leaf directories in a depth limited walk + symlinks to directories when link following is disabled in the underlying walk
`all_paths`: interleaved output of `all_dir_paths` and `file_paths` (previously: interleaved output of `dir_paths` and `file_paths`)

**Comment by ncoghlan** [comment]
PR #13 should address both this and #11 - if it looks good to you, I'll merge it and push out a 0.4 release (if not this week, then next weekend)

**Comment by ncoghlan** [comment]
Rendered version of the docs updates: http://walkdir.readthedocs.io/en/issue-12-all_dir_paths/

**Comment by palaviv** [comment]
The documentation and PR #13 looks great. I added another small PR #14. As #14 is a small issue we can release with it or without it as you would like.

**Comment by ncoghlan** [comment]
Resolved by #13

**Comment by ncoghlan** [comment]
The recent changes have all been released to PyPI: https://pypi.python.org/pypi/walkdir
