### ISSUE TITLE
Transfer maintenance to Aviv Palivoda

### ISSUE THREAD

**Issue by ncoghlan** [ncoghlan/walkdir#17]
Making a checklist of all the items needed to give @palaviv full publication access :)

- [x] GitHub contributor access (this should cover Travis CI as well)
- [x] ReadTheDocs project admin access (needs RTD account name)
- [x] PyPI project maintainer access (needs PyPI account name)
- [x] Update the README to remove the request-for-maintainer notice
- [x] Update the project metadata appropriately

**Comment by ncoghlan** [comment]
https://github.com/ncoghlan/walkdir/commit/13b801343ca9fde84c97a2df9570ddb5a420f0c9 updates the README.

@palaviv I'll leave updating the actual metadata to you as part of preparing the next release :)

For the other two items, are you also palaviv on PyPI and ReadTheDocs?

**Comment by palaviv** [comment]
Yes for both

**Comment by ncoghlan** [comment]
Cool! You have full access on both PyPI and RTD now :)

**Comment by ncoghlan** [comment]
Regarding the metadata update, the key point there will be to set the `maintainer` and `maintainer_email` keywords appropriately in setup.py: https://packaging.python.org/specifications/core-metadata/#maintainer

**Comment by palaviv** [comment]
Updated the metadata :)
