### ISSUE TITLE
Decide if bottom-up/depth-first traversal is supported or not

### ISSUE THREAD

**Issue by ncoghlan** [ncoghlan/walkdir#7]
Several of the filters in walkdir assume they can modify the tree traversal by altering the subdirectory list. Perhaps the module should just declare that only top-down/breadth-first is explicitly supported, and traversal related filters like `min_depth` and `max_depth` won't work as expected when the underlying walk has "topdown=False" specified?

**Comment by ncoghlan** [comment]
This could also be documented on a filter by filter basis (e.g. file filtering by name will work with a bottom-up traversal, but directory filtering won't, since the child directories get visited before the parent one)

**Comment by ncoghlan** [comment]
I believe the breakdown is as follows.

Requires top-down/breadth-first traversal for the subdirectory list manipulation to take effect:
- include_dirs
- exclude_dirs
- limit_depth
- min_depth

Also supports bottom-up/depth-first traversal:
- include_files
- include_dirs

`min_depth` has the additional restriction of needing to come after other subdirectory filters if you want the directories at the minimum depth to be filtered.

**Comment by palaviv** [comment]
I am not sure if "include_dirs" would work on bottom-up as it changes the subdirs list. Also I think "exclude_files" will work on both. Would you like me to do the PR with the work needed or would you do this?

**Comment by ncoghlan** [comment]
Hah, that was a copy-and-paste error - indeed, the second entry in the second list was supposed to be "exclude_files" but I edited the wrong part of the name and didn't notice.

I'll do a general docs update today, including the release note entries, as part of preparing a new release with all your changes, so there's no need to send a PR for this one.

**Comment by ncoghlan** [comment]
Addressed in https://github.com/ncoghlan/walkdir/commit/ec5410b25d2c2849e08eb154ecfaf34e7753fe3b
